import pytest


@pytest.fixture()
def qq_forecast_resp():
    return {
        "data": {
            "air": {
                "aqi": 104,
                "aqi_level": 3,
                "aqi_name": "轻度污染",
                "co": "2.1",
                "no2": "40",
                "o3": "42",
                "pm10": "120",
                "pm2.5": "78",
                "so2": "10",
                "update_time": "20190526070000",
            },
            "alarm": {
                "0": {
                    "city": "朝阳区",
                    "county": "",
                    "detail": "朝阳区气象台01日06时40分发布大风蓝色预警,预计，1日10时至20时朝阳区有4级左右偏南风，阵风可达7级左右，请注意防范。（预警信息来源：国家预警信息发布中心）",
                    "info": "202006010640545112大风蓝色",
                    "level_code": "01",
                    "level_name": "蓝色",
                    "province": "北京市",
                    "type_code": "05",
                    "type_name": "大风",
                    "update_time": "2020-06-01 06:40",
                    "url": "1010103-20200601064000-0501.html",
                },
                "1": {
                    "city": "",
                    "county": "",
                    "detail": "市气象台2020年6月01日06时00分发布大风蓝色预警信号：预计，1日10时至20时本市大部分地区有4级左右偏南风，阵风可达7级左右，请注意防范。（预警信息来源：国家预警信息发布中心）",
                    "info": "202006010600545112大风蓝色",
                    "level_code": "01",
                    "level_name": "蓝色",
                    "province": "北京市",
                    "type_code": "05",
                    "type_name": "大风",
                    "update_time": "2020-06-01 06:00",
                    "url": "10101-20200601060040-0501.html",
                },
            },
            "forecast_1h": {
                "0": {
                    "degree": "29",
                    "update_time": "20200601130000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "1": {
                    "degree": "29",
                    "update_time": "20200601140000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "10": {
                    "degree": "20",
                    "update_time": "20200601230000",
                    "weather": "多云",
                    "weather_code": "01",
                    "weather_short": "多云",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "11": {
                    "degree": "19",
                    "update_time": "20200602000000",
                    "weather": "多云",
                    "weather_code": "01",
                    "weather_short": "多云",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "12": {
                    "degree": "18",
                    "update_time": "20200602010000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "13": {
                    "degree": "17",
                    "update_time": "20200602020000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "14": {
                    "degree": "16",
                    "update_time": "20200602030000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "15": {
                    "degree": "16",
                    "update_time": "20200602040000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西风",
                    "wind_power": "3",
                },
                "16": {
                    "degree": "16",
                    "update_time": "20200602050000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "17": {
                    "degree": "17",
                    "update_time": "20200602060000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西风",
                    "wind_power": "3",
                },
                "18": {
                    "degree": "17",
                    "update_time": "20200602070000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西风",
                    "wind_power": "4",
                },
                "19": {
                    "degree": "18",
                    "update_time": "20200602080000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "2": {
                    "degree": "29",
                    "update_time": "20200601150000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "20": {
                    "degree": "22",
                    "update_time": "20200602090000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西风",
                    "wind_power": "3",
                },
                "21": {
                    "degree": "26",
                    "update_time": "20200602100000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "22": {
                    "degree": "29",
                    "update_time": "20200602110000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "3",
                },
                "23": {
                    "degree": "30",
                    "update_time": "20200602120000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "24": {
                    "degree": "31",
                    "update_time": "20200602130000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "3",
                },
                "25": {
                    "degree": "32",
                    "update_time": "20200602140000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "4",
                },
                "26": {
                    "degree": "32",
                    "update_time": "20200602150000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "4",
                },
                "27": {
                    "degree": "32",
                    "update_time": "20200602160000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "6",
                },
                "28": {
                    "degree": "32",
                    "update_time": "20200602170000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "5",
                },
                "29": {
                    "degree": "32",
                    "update_time": "20200602180000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "5",
                },
                "3": {
                    "degree": "29",
                    "update_time": "20200601160000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "30": {
                    "degree": "29",
                    "update_time": "20200602190000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "5",
                },
                "31": {
                    "degree": "27",
                    "update_time": "20200602200000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "5",
                },
                "32": {
                    "degree": "26",
                    "update_time": "20200602210000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "33": {
                    "degree": "25",
                    "update_time": "20200602220000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "34": {
                    "degree": "23",
                    "update_time": "20200602230000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "4",
                },
                "35": {
                    "degree": "23",
                    "update_time": "20200603000000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "3",
                },
                "36": {
                    "degree": "22",
                    "update_time": "20200603010000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "南风",
                    "wind_power": "3",
                },
                "37": {
                    "degree": "22",
                    "update_time": "20200603020000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "38": {
                    "degree": "21",
                    "update_time": "20200603030000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东南风",
                    "wind_power": "4",
                },
                "39": {
                    "degree": "20",
                    "update_time": "20200603040000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西风",
                    "wind_power": "3",
                },
                "4": {
                    "degree": "29",
                    "update_time": "20200601170000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "5",
                },
                "40": {
                    "degree": "20",
                    "update_time": "20200603050000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "41": {
                    "degree": "21",
                    "update_time": "20200603060000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西风",
                    "wind_power": "3",
                },
                "42": {
                    "degree": "23",
                    "update_time": "20200603070000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "43": {
                    "degree": "24",
                    "update_time": "20200603080000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "西南风",
                    "wind_power": "4",
                },
                "44": {
                    "degree": "25",
                    "update_time": "20200603090000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东风",
                    "wind_power": "4",
                },
                "45": {
                    "degree": "27",
                    "update_time": "20200603100000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东北风",
                    "wind_power": "4",
                },
                "46": {
                    "degree": "28",
                    "update_time": "20200603110000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "北风",
                    "wind_power": "4",
                },
                "47": {
                    "degree": "29",
                    "update_time": "20200603120000",
                    "weather": "晴",
                    "weather_code": "00",
                    "weather_short": "晴",
                    "wind_direction": "东风",
                    "wind_power": "4",
                },
                "5": {
                    "degree": "24",
                    "update_time": "20200601180000",
                    "weather": "雷阵雨",
                    "weather_code": "04",
                    "weather_short": "雷阵雨",
                    "wind_direction": "西风",
                    "wind_power": "4",
                },
                "6": {
                    "degree": "24",
                    "update_time": "20200601190000",
                    "weather": "雷阵雨",
                    "weather_code": "04",
                    "weather_short": "雷阵雨",
                    "wind_direction": "西风",
                    "wind_power": "6",
                },
                "7": {
                    "degree": "24",
                    "update_time": "20200601200000",
                    "weather": "雷阵雨",
                    "weather_code": "04",
                    "weather_short": "雷阵雨",
                    "wind_direction": "西南风",
                    "wind_power": "3",
                },
                "8": {
                    "degree": "21",
                    "update_time": "20200601210000",
                    "weather": "多云",
                    "weather_code": "01",
                    "weather_short": "多云",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
                "9": {
                    "degree": "21",
                    "update_time": "20200601220000",
                    "weather": "多云",
                    "weather_code": "01",
                    "weather_short": "多云",
                    "wind_direction": "东南风",
                    "wind_power": "3",
                },
            },
            "forecast_24h": {
                "0": {
                    "day_weather": "小雨",
                    "day_weather_code": "07",
                    "day_weather_short": "小雨",
                    "day_wind_direction": "西北风",
                    "day_wind_direction_code": "7",
                    "day_wind_power": "4",
                    "day_wind_power_code": "1",
                    "max_degree": "26",
                    "min_degree": "14",
                    "night_weather": "晴",
                    "night_weather_code": "00",
                    "night_weather_short": "晴",
                    "night_wind_direction": "西风",
                    "night_wind_direction_code": "6",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-05-31",
                },
                "1": {
                    "day_weather": "雷阵雨",
                    "day_weather_code": "04",
                    "day_weather_short": "雷阵雨",
                    "day_wind_direction": "西南风",
                    "day_wind_direction_code": "5",
                    "day_wind_power": "5",
                    "day_wind_power_code": "2",
                    "max_degree": "30",
                    "min_degree": "16",
                    "night_weather": "多云",
                    "night_weather_code": "01",
                    "night_weather_short": "多云",
                    "night_wind_direction": "西南风",
                    "night_wind_direction_code": "5",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-06-01",
                },
                "2": {
                    "day_weather": "晴",
                    "day_weather_code": "00",
                    "day_weather_short": "晴",
                    "day_wind_direction": "南风",
                    "day_wind_direction_code": "4",
                    "day_wind_power": "5",
                    "day_wind_power_code": "2",
                    "max_degree": "33",
                    "min_degree": "20",
                    "night_weather": "晴",
                    "night_weather_code": "00",
                    "night_weather_short": "晴",
                    "night_wind_direction": "西南风",
                    "night_wind_direction_code": "5",
                    "night_wind_power": "4",
                    "night_wind_power_code": "1",
                    "time": "2020-06-02",
                },
                "3": {
                    "day_weather": "晴",
                    "day_weather_code": "00",
                    "day_weather_short": "晴",
                    "day_wind_direction": "北风",
                    "day_wind_direction_code": "8",
                    "day_wind_power": "4",
                    "day_wind_power_code": "1",
                    "max_degree": "32",
                    "min_degree": "19",
                    "night_weather": "晴",
                    "night_weather_code": "00",
                    "night_weather_short": "晴",
                    "night_wind_direction": "北风",
                    "night_wind_direction_code": "8",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-06-03",
                },
                "4": {
                    "day_weather": "多云",
                    "day_weather_code": "01",
                    "day_weather_short": "多云",
                    "day_wind_direction": "东南风",
                    "day_wind_direction_code": "3",
                    "day_wind_power": "4",
                    "day_wind_power_code": "1",
                    "max_degree": "29",
                    "min_degree": "18",
                    "night_weather": "多云",
                    "night_weather_code": "01",
                    "night_weather_short": "多云",
                    "night_wind_direction": "东南风",
                    "night_wind_direction_code": "3",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-06-04",
                },
                "5": {
                    "day_weather": "多云",
                    "day_weather_code": "01",
                    "day_weather_short": "多云",
                    "day_wind_direction": "东北风",
                    "day_wind_direction_code": "1",
                    "day_wind_power": "3",
                    "day_wind_power_code": "0",
                    "max_degree": "30",
                    "min_degree": "18",
                    "night_weather": "晴",
                    "night_weather_code": "00",
                    "night_weather_short": "晴",
                    "night_wind_direction": "东南风",
                    "night_wind_direction_code": "3",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-06-05",
                },
                "6": {
                    "day_weather": "多云",
                    "day_weather_code": "01",
                    "day_weather_short": "多云",
                    "day_wind_direction": "东南风",
                    "day_wind_direction_code": "3",
                    "day_wind_power": "3",
                    "day_wind_power_code": "0",
                    "max_degree": "30",
                    "min_degree": "19",
                    "night_weather": "多云",
                    "night_weather_code": "01",
                    "night_weather_short": "多云",
                    "night_wind_direction": "东南风",
                    "night_wind_direction_code": "3",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-06-06",
                },
                "7": {
                    "day_weather": "多云",
                    "day_weather_code": "01",
                    "day_weather_short": "多云",
                    "day_wind_direction": "东南风",
                    "day_wind_direction_code": "3",
                    "day_wind_power": "3",
                    "day_wind_power_code": "0",
                    "max_degree": "33",
                    "min_degree": "21",
                    "night_weather": "多云",
                    "night_weather_code": "01",
                    "night_weather_short": "多云",
                    "night_wind_direction": "东南风",
                    "night_wind_direction_code": "3",
                    "night_wind_power": "3",
                    "night_wind_power_code": "0",
                    "time": "2020-06-07",
                },
            },
            "index": {
                "airconditioner": {
                    "detail": "天气热，到中午的时候您将会感到有点热，因此建议在午后较热时开启制冷空调。",
                    "info": "部分时间开启",
                    "name": "空调开启",
                },
                "allergy": {
                    "detail": "天气条件不易诱发过敏，有降水，特殊体质人群应预防感冒可能引发的过敏。",
                    "info": "不易发",
                    "name": "过敏",
                },
                "carwash": {
                    "detail": "不宜洗车，未来24小时内有雨，如果在此期间洗车，雨水和路上的泥水可能会再次弄脏您的爱车。",
                    "info": "不宜",
                    "name": "洗车",
                },
                "chill": {
                    "detail": "温度未达到风寒所需的低温，稍作防寒准备即可。",
                    "info": "无",
                    "name": "风寒",
                },
                "clothes": {
                    "detail": "天气热，建议着短裙、短裤、短薄外套、T恤等夏季服装。",
                    "info": "热",
                    "name": "穿衣",
                },
                "cold": {
                    "detail": "各项气象条件适宜，发生感冒机率较低。但请避免长期处于空调房间中，以防感冒。",
                    "info": "少发",
                    "name": "感冒",
                },
                "comfort": {
                    "detail": "白天天气较热，虽然有雨，但仍然无法削弱较高气温给人们带来的暑意，这种天气会让您感到不很舒适。",
                    "info": "较不舒适",
                    "name": "舒适度",
                },
                "diffusion": {
                    "detail": "气象条件有利于空气污染物稀释、扩散和清除。",
                    "info": "良",
                    "name": "空气污染扩散条件",
                },
                "dry": {
                    "detail": "有降水，路面潮湿，车辆易打滑，请小心驾驶。",
                    "info": "潮湿",
                    "name": "路况",
                },
                "drying": {
                    "detail": "有降水，不适宜晾晒。若需要晾晒，请在室内准备出充足的空间。",
                    "info": "不宜",
                    "name": "晾晒",
                },
                "fish": {
                    "detail": "天气不好，有风，不适合垂钓。",
                    "info": "不宜",
                    "name": "钓鱼",
                },
                "heatstroke": {
                    "detail": "天气不热，在炎炎夏日中十分难得，可以告别暑气漫漫啦~",
                    "info": "无中暑风险",
                    "name": "中暑",
                },
                "makeup": {
                    "detail": "天气较热，建议用露质面霜打底，水质无油粉底霜，透明粉饼，粉质胭脂。",
                    "info": "去油",
                    "name": "化妆",
                },
                "mood": {
                    "detail": "有降水，雨水可能会使心绪无端地挂上轻愁，与其因下雨而无精打采，不如放松心情，好好欣赏一下雨景。你会发现雨中的世界是那般洁净温和、清新葱郁。",
                    "info": "较差",
                    "name": "心情",
                },
                "morning": {
                    "detail": "有降水，且风力稍大，请尽量避免户外晨练，若坚持晨练请带上雨具。",
                    "info": "不宜",
                    "name": "晨练",
                },
                "sports": {
                    "detail": "有降水，且风力较强，推荐您在室内进行低强度运动；若坚持户外运动，请选择避雨防风的地点。",
                    "info": "较不宜",
                    "name": "运动",
                },
                "sunglasses": {
                    "detail": "白天有降水天气，视线较差，不需要佩戴太阳镜",
                    "info": "不需要",
                    "name": "太阳镜",
                },
                "sunscreen": {
                    "detail": "属弱紫外辐射天气，长期在户外，建议涂擦SPF在8-12之间的防晒护肤品。",
                    "info": "弱",
                    "name": "防晒",
                },
                "time": "20200601",
                "tourism": {
                    "detail": "有降水，外出请注意防雷。风稍大，稍热，等雨过去，还是可以外出游玩的哦。",
                    "info": "一般",
                    "name": "旅游",
                },
                "traffic": {
                    "detail": "有降水，路面湿滑，刹车距离延长，事故易发期，注意车距，务必小心驾驶。",
                    "info": "一般",
                    "name": "交通",
                },
                "ultraviolet": {
                    "detail": "属弱紫外线辐射天气，无需特别防护。若长期在户外，建议涂擦SPF在8-12之间的防晒护肤品。",
                    "info": "最弱",
                    "name": "紫外线强度",
                },
                "umbrella": {
                    "detail": "有降水，如果您要短时间外出的话可不必带雨伞。",
                    "info": "带伞",
                    "name": "雨伞",
                },
            },
            "limit": {"tail_number": "不限行", "time": "20200601"},
            "observe": {
                "degree": "29",
                "humidity": "30",
                "precipitation": "0.0",
                "pressure": "998",
                "update_time": "202006011323",
                "weather": "晴",
                "weather_code": "00",
                "weather_short": "晴",
                "wind_direction": "5",
                "wind_power": "2",
            },
            "rise": {
                "0": {
                    "sunrise": "04:47",
                    "sunset": "19:36",
                    "time": "20200601",
                },
                "1": {
                    "sunrise": "04:47",
                    "sunset": "19:37",
                    "time": "20200602",
                },
                "10": {
                    "sunrise": "04:45",
                    "sunset": "19:42",
                    "time": "20200611",
                },
                "11": {
                    "sunrise": "04:45",
                    "sunset": "19:43",
                    "time": "20200612",
                },
                "12": {
                    "sunrise": "04:44",
                    "sunset": "19:43",
                    "time": "20200613",
                },
                "13": {
                    "sunrise": "04:44",
                    "sunset": "19:44",
                    "time": "20200614",
                },
                "14": {
                    "sunrise": "04:45",
                    "sunset": "19:44",
                    "time": "20200615",
                },
                "2": {
                    "sunrise": "04:46",
                    "sunset": "19:38",
                    "time": "20200603",
                },
                "3": {
                    "sunrise": "04:46",
                    "sunset": "19:38",
                    "time": "20200604",
                },
                "4": {
                    "sunrise": "04:46",
                    "sunset": "19:39",
                    "time": "20200605",
                },
                "5": {
                    "sunrise": "04:45",
                    "sunset": "19:40",
                    "time": "20200606",
                },
                "6": {
                    "sunrise": "04:45",
                    "sunset": "19:40",
                    "time": "20200607",
                },
                "7": {
                    "sunrise": "04:45",
                    "sunset": "19:41",
                    "time": "20200608",
                },
                "8": {
                    "sunrise": "04:45",
                    "sunset": "19:41",
                    "time": "20200609",
                },
                "9": {
                    "sunrise": "04:45",
                    "sunset": "19:42",
                    "time": "20200610",
                },
            },
            "tips": {"observe": {"0": "你若安好，便是晴天~", "1": "现在的温度比较舒适~"}},
        },
        "message": "OK",
        "status": 200,
    }
